config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :cryptos

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
	validates :name, presence: true, 
		length: { minimum: 5 }
	validates :short_name, presence: true,
		length: { maximum: 5 }
end

app/models/info_at_time.rb
class InfoAtTime < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
	

	def index
		@cryptos = Crypto.all
	end


	def show
    	@crypto = Crypto.find(params[:id])
  	end


	def new
		@crypto = Crypto.new
	end

	def edit
		@crypto = Crypto.find(params[:id])
	end


	def create
		@crypto = Crypto.new(crypto_params)

		if @crypto.save
			redirect_to @crypto
		else
			render 'new'
		end
	end


	def update
		@crypto = Crypto.find(params[:id])
	 
		if @crypto.update(crypto_params)
			redirect_to @crypto
		else
			render 'edit'
		end
	end


	def destroy
		@crypto = Crypto.find(params[:id])
		@crypto.destroy
 
		redirect_to cryptos_path
	end


	private
		def crypto_params
			params.require(:crypto).permit(:name, :short_name, :date_of_birth)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cryptos/_form.html.erb
<%= form_with(model: @crypto) do |form| %>
 
  <% if @crypto.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@crypto.errors.count, "error") %> prohibited
        this crypto from being saved:
      </h2>
      <ul>
        <% @crypto.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :short_name %><br>
    <%= form.text_area :short_name %>
  </p>

  <p>
    <%= form.label :date_of_birth %><br>
    <%= form.date_field :date_of_birth %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/cryptos/edit.html.erb
<h1>Edit crypto</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', cryptos_path %>

app/views/cryptos/index.html.erb
<h1>Listing Cryptos</h1>

<%= link_to 'New Crypto', new_crypto_path %>
<br><br> 
<table>
  <tr>
    <th>Name</th>
    <th>Short Name</th>
    <th>Date of Birth</th>
    <th colspan="3"></th>
  </tr>
 
  <% @cryptos.each do |crypto| %>
    <tr>
      <td><%= crypto.name %></td>
      <td><%= crypto.short_name %></td>
      <td><%= crypto.date_of_birth %></td>
      <td><%= link_to 'Show', crypto_path(crypto) %></td>
      <td><%= link_to 'Edit', edit_crypto_path(crypto) %></td>
      <td><%= link_to 'Delete', crypto_path(crypto),
        method: :delete,
        data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

app/views/cryptos/new.html.erb
<h1>New Crypto</h1>
  
<%= render 'form' %>

<%= link_to 'Back', cryptos_path %>

app/views/cryptos/show.html.erb
<h1>Show</h1>
<p>
  <strong>Name:</strong>
  <%= @crypto.name %>
</p>
 
<p>
  <strong>Short Name:</strong>
  <%= @crypto.short_name %>
</p>

<p>
  <strong>Date of Birth:</strong>
  <%= @crypto.date_of_birth %>
</p>
<%= link_to 'Back', cryptos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoCurrencyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Cryptos</h1>
<%= link_to 'My Crypto', controller: 'cryptos' %>